# -*- coding: utf-8 -*-
"""Regresi_Linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMHafh-NFmjqRFySwzqFu3JXbdxr1wQP

Gina Nabila (21120122130055)

**Metode Numerik - Kelas D**

**Aplikasi Regresi Linear**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Memuat data dari file CSV
file_path = '/content/drive/MyDrive/Colab Notebooks/Student_Performance.csv'
data = pd.read_csv(file_path)

# Mempersiapkan data
# Menggunakan kolom 'hours studied' sebagai durasi belajar (TB) dan 'performance index' sebagai nilai ujian (NT)
data = data.dropna()  # Menghapus baris yang memiliki nilai NaN
X = data[['Hours Studied']].values  # Mengambil kolom hours studied sebagai variabel independen
y = data['Performance Index'].values  # Mengambil kolom performance index sebagai variabel dependen

# Melakukan regresi linear menggunakan Scikit-Learn
model = LinearRegression()
model.fit(X, y)
y_pred = model.predict(X)

# Membuat plot hasil regresi
plt.scatter(X, y, color='royalblue', label='Data Sebenarnya')
plt.plot(X, y_pred, color='hotpink', linewidth=2, label='Garis Regresi')
plt.xlabel('Waktu Belajar')
plt.ylabel('Nilai Ujian')
plt.title('Hubungan waktu belajar terhadap nilai ujian')
plt.legend()
plt.show()

# Menghitung dan menampilkan nilai galat RMS (Root Mean Square Error)
rms_error = np.sqrt(mean_squared_error(y, y_pred))
print(f'Galat RMS: {rms_error}')