# -*- coding: utf-8 -*-
"""Regresi_Eksponensial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qu9KUAH-wBVZ4bHXSX5WO_rtlYTUMIum

Gina Nabila (21120122130055)

**Metode Numerik - Kelas D**

**Aplikasi Regresi Eksponensial**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from scipy.optimize import curve_fit

# Memuat data dari file CSV
file_path = '/content/drive/MyDrive/Colab Notebooks/Student_Performance.csv'
data = pd.read_csv(file_path)

# Mempersiapkan data
data = data.dropna()  # Menghapus baris yang memiliki nilai NaN
X = data['Hours Studied'].values  # Mengambil kolom hours studied sebagai variabel independen
y = data['Performance Index'].values  # Mengambil kolom performance index sebagai variabel dependen

# Mendefinisikan fungsi eksponensial
def exponential_model(x, a, b):
    return a * np.exp(b * x)

# Melakukan regresi eksponensial menggunakan curve_fit dari scipy
popt, pcov = curve_fit(exponential_model, X, y)
y_pred = exponential_model(X, *popt)

# Membuat plot hasil regresi
plt.scatter(X, y, color='royalblue', label='Data Sebenarnya')
plt.plot(X, y_pred, color='hotpink', linewidth=2, label='Garis Regresi Eksponensial')
plt.xlabel('Waktu Belajar')
plt.ylabel('Nilai Ujian')
plt.title('Hubungan Waktu Belajar terhadap Nilai Ujian')
plt.legend()
plt.show()

# Menghitung dan menampilkan nilai galat RMS (Root Mean Square Error)
rms_error = np.sqrt(mean_squared_error(y, y_pred))
print(f'Galat RMS: {rms_error}')